# Generated by Django 5.2 on 2025-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('cause', models.CharField(choices=[('POOR', 'فقرا'), ('SCHOOL', 'مدرسه\u200cسازی'), ('HEALTH', 'درمان بیماران')], max_length=20, verbose_name='بابت')),
                ('status', models.CharField(choices=[('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('PENDING', 'در انتظار')], default='PENDING', max_length=10, verbose_name='وضعیت پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری بانک')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد داخلی/رسید')),
                ('gateway_response', models.TextField(blank=True, null=True, verbose_name='پاسخ بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
            ],
        ),
    ]
