# Generated by Django 5.2 on 2025-06-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_persona'),
        ('donation', '0002_donation_wallet_transaction'),
        ('martyrs', '0003_alter_martyr_options_alter_martyrmemory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'صدقه', 'verbose_name_plural': 'صدقات'},
        ),
        migrations.AddField(
            model_name='donation',
            name='martyr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='martyrs.martyr', verbose_name='شهید مرتبط'),
        ),
        migrations.AddField(
            model_name='donation',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='accounts.persona', verbose_name='جاودانه مرتبط'),
        ),
    ]
