# Generated by Django 5.2 on 2025-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donation_persona_donation_eternal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.CharField(choices=[('CHARITY', 'صدقه'), ('SAEDAT_SHARE', 'سهم سادات'), ('KAFARA', 'کفاره'), ('GHORBANI', 'قربانی')], max_length=20, verbose_name='بابت'),
        ),
    ]
