# Generated by Django 5.2 on 2025-07-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد (انگلیسی یا لاتین)')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان (فارسی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'علت صدقه',
                'verbose_name_plural': 'علل صدقه',
            },
        ),
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donation.donationcause', verbose_name='بابت'),
        ),
    ]
