# Generated by Django 5.2 on 2025-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_donationcause_alter_donation_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcause',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد (انگلیسی یا لاتین)'),
        ),
    ]
