# Generated by Django 5.2 on 2025-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_alter_donationcause_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcause',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='سیستمی (برای استفاده داخلی سایت)'),
        ),
    ]
