# Generated by Django 5.2 on 2025-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_donationcause_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='extra_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد اضافی (مثلاً کد کوپن، یا کد پیگیری داخلی)'),
        ),
    ]
