# Generated by Django 5.2 on 2025-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donation_extra_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='extra_code',
        ),
        migrations.AddField(
            model_name='donation',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای اضافی'),
        ),
    ]
