# Generated by Django 5.2 on 2025-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_remove_donation_extra_code_donation_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
