# Generated by Django 5.2 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_donation_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('gateway', 'Gateway')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
    ]
