# Generated by Django 5.2 on 2025-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='اگر صفر باشد محدودیتی ندارد.', verbose_name='سقف ارسال روزانه'),
        ),
    ]
