# Generated by Django 5.2 on 2025-07-19 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_daily_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.URLField(verbose_name='آدرس لینک')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='news.news')),
            ],
        ),
    ]
