# Generated by Django 5.2 on 2025-07-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0007_alter_donationcause_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گروه نوتیفیکیشن')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='اجباری است؟')),
                ('hidden', models.BooleanField(default=False, verbose_name='مخفی است؟')),
                ('send_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال پیام (تومان)')),
                ('needs_approval', models.BooleanField(default=False, verbose_name='نیاز به تایید مدیر دارد؟')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی است؟')),
                ('allowed_senders', models.ManyToManyField(blank=True, related_name='allowed_notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکنندگان مجاز')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='مدیران گروه')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.PositiveIntegerField(verbose_name='تعداد کوپن خریداری شده')),
                ('quantity_used', models.PositiveIntegerField(default=0, verbose_name='تعداد کوپن مصرف شده')),
                ('donation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.donation', verbose_name='رکورد پرداخت صدقه مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='notification.notificationgroup', verbose_name='گروه نوتیفیکیشن')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('description', models.TextField(verbose_name='توضیحات پیام')),
                ('eternal_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID جاودانه مرتبط')),
                ('news_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID خبر مرتبط')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('SENT', 'ارسال شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده پیام')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notification.notificationgroup', verbose_name='گروه نوتیفیکیشن')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='notification.notificationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مشاهده')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='notification.notification', verbose_name='نوتیفیکیشن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_seen', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
