# Generated by Django 5.2 on 2025-07-10 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationcoupon',
            unique_together={('user', 'group')},
        ),
    ]
