# Generated by Django 5.2 on 2025-07-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notificationcoupon_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expire_days',
            field=models.PositiveIntegerField(default=30, verbose_name='مدت اعتبار پیام (روز)'),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='default_expire_days',
            field=models.PositiveIntegerField(default=30, verbose_name='مدت پیش\u200cفرض اعتبار پیام (روز)'),
        ),
    ]
