# Generated by Django 5.2 on 2025-07-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eternals', '0001_initial'),
        ('news', '0006_category_daily_limit'),
        ('notification', '0003_notification_expire_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='eternal_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='news_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='eternal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eternals.eternals', verbose_name='جاودانه مرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news', verbose_name='خبر مرتبط'),
        ),
    ]
