# Generated by Django 5.2 on 2025-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationcouponpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcoupon',
            name='quantity_reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کوپن رزرو شده'),
        ),
    ]
