# Generated by Django 5.2 on 2025-07-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationcoupon_quantity_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='coupon_reserved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationcoupon', verbose_name='کوپن رزروشده'),
        ),
    ]
