# Generated by Django 5.2 on 2025-06-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_allowed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_categories',
        ),
    ]
