# Generated by Django 5.2 on 2025-06-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eternals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('known_as', models.CharField(blank=True, max_length=100, null=True, verbose_name='معروف به')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاریخ فوت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='eternals/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جاودانه',
                'verbose_name_plural': 'جاودانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CondolenceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام تسلیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolences', to='accounts.persona')),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolences', to='eternals.eternals')),
            ],
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony', models.TextField(verbose_name='مراسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceremonies', to=settings.AUTH_USER_MODEL)),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceremonies', to='eternals.eternals')),
            ],
        ),
    ]
