# Generated by Django 5.2 on 2025-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Martyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('last_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('martyr_region', models.CharField(blank=True, max_length=100, null=True)),
                ('martyr_place', models.CharField(blank=True, max_length=100, null=True)),
                ('martyr_date', models.DateField(blank=True, null=True)),
                ('grave_place', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='martyrs/photos/')),
            ],
        ),
    ]
