# Generated by Django 5.2 on 2025-05-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MartyrMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='memories/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='memories/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('martyr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='martyrs.martyr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
