# Generated by Django 5.2 on 2025-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='bank_donation',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='related_donation',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='type',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='cause',
            field=models.CharField(blank=True, choices=[('POOR', 'فقرا'), ('SCHOOL', 'مدرسه\u200cسازی'), ('HEALTH', 'درمان بیماران')], max_length=20, null=True, verbose_name='بابت صدقه'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('PENDING', 'در انتظار')], default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CHARGE', 'شارژ کیف پول'), ('DONATION', 'پرداخت صدقه از کیف پول')], default='CHARGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی کیف پول (تومان)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ (تومان)'),
        ),
    ]
