# Generated by Django 5.2 on 2025-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع تراکنش'),
        ),
    ]
