# Generated by Django 5.2 on 2025-07-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_donationcause_alter_donation_cause'),
        ('wallet', '0003_wallettransaction_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='donation.donationcause'),
        ),
    ]
