# Generated by Django 5.2 on 2025-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallettransaction_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تراکنش'),
        ),
    ]
