# Generated by Django 5.2 on 2025-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallettransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CHARGE', 'شارژ کیف پول'), ('DONATION', 'پرداخت صدقه از کیف پول'), ('COUPON_PURCHASE', 'خرید کوپن ارسال پیام از کیف پول')], default='CHARGE', max_length=20),
        ),
    ]
